on:
  workflow_call:
    secrets:
      NEXUS_USER:
        required: true
      NEXUS_PASSWORD:
        required: true
    inputs:
      runs-on:
        type: string
        default: 'runner-oracle-dev'
        required: false
      registry_image:
        required: true
        type: string
      registry:
        required: true
        type: string
      docker_build_args:
        required: false
        type: string
      image_tag:
        required: true
        type: string

jobs:
  build-docker:
    name: Build docker image
    runs-on: runner-oracle-dev
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: docker build 
        env:
          TAG: ${{ inputs.image_tag }}
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_PASSWORD }}
          REGISTRY_IMAGE: ${{ inputs.registry_image }}
          DOCKER_BUILD_ARGS: ${{ inputs.docker_build_args }}
          REGISTRY: ${{ inputs.registry }}
        run: |
          docker login $REGISTRY -u $username -p $password
          docker build --push -t $REGISTRY_IMAGE:$TAG $DOCKER_BUILD_ARGS .
          docker rmi $REGISTRY_IMAGE:$TAG
          docker logout $REGISTRY