on:
  workflow_call:
    secrets:
      NEXUS_USER:
        required: true
      NEXUS_PASSWORD:
        required: true
    inputs:
      registry_image:
        required: true
        type: string
      registry:
        required: true
        type: string
      helm_repo:
        required: true
        type: string
      docker_build_args:
        required: false
        type: string
      project_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  build:
    name: Build docker image
    runs-on: runner-oracle-dev
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: docker build 
        env:
          TAG: ${{ inputs.image_tag }}
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_PASSWORD }}
          REGISTRY_IMAGE: ${{ inputs.registry_image }}
          DOCKER_BUILD_ARGS: ${{ inputs.docker_build_args }}
          REGISTRY: ${{ inputs.registry }}
        run: |
          echo ${{ inputs.image_tag }}
          docker login $REGISTRY -u $username -p $password
          docker build --push -t $REGISTRY_IMAGE:$TAG $DOCKER_BUILD_ARGS .
          docker rmi $REGISTRY_IMAGE:$TAG
          docker logout $REGISTRY
  deploy:
    name: Build helm chart
    runs-on: runner-oracle-dev
    needs: build
    steps: 
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: builld helm
        env:
          TAG: ${{ inputs.image_tag }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}
          PROJECT_NAME: ${{ inputs.project_name }}
          HELM_REPO: ${{ inputs.helm_repo }}
        run: |
          helm dependency update ./helm/$PROJECT_NAME/
          helm package ./helm/$PROJECT_NAME/ --app-version $TAG --version $TAG
          curl -u $username:$password $HELM_REPO --upload-file $PROJECT_NAME-$TAG.tgz